repos:
-   repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
    - id: black
      language_version: python3.10
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
    - id: isort
      name: isort (python)
-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
-   id: codespell
    name: codespell
    description: Checks for common misspellings in text files.
    entry: codespell
    language: python
    types: [text]
