name: tests

on: [push, pull_request]

jobs:
  build:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.13']
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Test runtime dependencies
        run: |
          uv run --no-dev -p python${{ matrix.python-version }} -- python -c '
          from cihai import _internal, data, config, constants, conversion, core, db, exc, extend, log, types, utils, __about__, __version__
          from cihai._internal import config_reader, types
          from cihai.data import decomp, unihan
          from cihai.data.unihan import bootstrap, constants, dataset
          from unihan_etl import __version__ as __unihan_etl_version__
          print("cihai version:", __version__)
          print("unihan_etl version:", __unihan_etl_version__)
          '

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Print python versions
        run: |
          python -V
          uv run python -V

      - name: Lint with ruff check
        run: uv run ruff check .

      - name: Format with ruff format
        run: uv run ruff format . --check

      - name: Lint with mypy
        run: uv run mypy .

      - name: Test with pytest
        run: uv run py.test --cov=./ --cov-report=xml

      - name: Test with pytest
        run: uv run ./examples/basic_usage.py

      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')

    strategy:
      matrix:
        python-version: ['3.13']

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Build package
        run: uv build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip_existing: true
