__title__ = 'cihai'
__package_name__ = 'cihai'
__version__ = '0.6.1'
__description__ = 'Python API for CJK datasets. Part of the cihai project.'
__author__ = 'Tony Narlock'
__email__ = 'tony@git-pull.com'
__license__ = 'MIT'
__copyright__ = 'Copyright 2013-2017 Tony Narlock'
